---
root: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  sourceType: "module"
plugins:
  - "react"
env:
  es6: true
  node: true
  browser: true
globals:
  device: false
  IScroll: false
  Velocity: false
  ScrollMagic: false
rules:
  comma-dangle: ["warn", "only-multiline"]
  comma-spacing: ["warn", {before: false, after: true}]
  comma-style: ["warn", "last", {exceptions: {VariableDeclaration: true}}]

  no-console: "warn"
  no-debugger: "warn"
  no-unused-vars: "warn"

  react/display-name: "off"
  react/prop-types: "off"
